# JAGT1806/reusables-workflows/.github/workflows/on-release-merged.yml>
name: "[Reusable] - On releas PR merged (bump patch & propagate)"

on:
  workflow_call:
    inputs:
      release_branch:
        required: true
        type: string
      next_release_branch:
        required: true
        type: string
      propagate_to_develop:
        required: false
        type: boolean
        default: true
      packaging:
        required: true
        type: string
        default: 'maven'
        description: 'maven | gradle'
    outputs:
      new_version:
        description: New version after bump
        value: ${{ jobs.bump_and_tag.outputs.new_version }}
      propagated_branches:
        description: Branches successfully propagated to
        value: ${{ jobs.propagate.outputs.propagated_branches }}

jobs:
  bump_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup Git
        uses: JAGT1806/repo-actions/.github/actions/setup-git@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout release
        run: |
          git checkout ${{ inputs.release_branch }}
          git pull origin ${{ inputs.release_branch }}

      - name: Read current Maven version
        if: ${{ inputs.packaging == 'maven' }}
        id: read-maven
        uses: JAGT1806/repo-actions/.github/actions/read-version-maven@main

      - name: Read current Gradle version
        if: ${{ inputs.packaging == 'gradle' }}
        id: read-gradle
        uses: JAGT1806/repo-actions/.github/actions/read-version-gradle@main

      - name: Get version from previous step
        id: read
        run: |
          if [ "${{ inputs.packaging }}" = "maven" ]; then
            echo "version=${{ steps.read-maven.outputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.read-gradle.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Bump patch
        id: bump
        uses: JAGT1806/repo-actions/.github/actions/bump-patch@main
        with:
          version: ${{ steps.read.outputs.version }}

      - name: Set bumped Maven version
        if: ${{ inputs.packaging == 'maven' }}
        uses: JAGT1806/repo-actions/.github/actions/set-version-maven@main
        with:
          version: ${{ steps.bump.outputs.new_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set bumped Gradle version
        if: ${{ inputs.packaging == 'gradle' }}
        uses: JAGT1806/repo-actions/.github/actions/set-version-gradle@main
        with:
          version: ${{ steps.bump.outputs.new_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag for new versopm
        uses: JAGT1806/repo-actions/.github/actions/create-tag@main
        with:
          tag: ${{ steps.bump.outputs.new_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  propagate:
    runs-on: ubuntu-latest
    needs: bump_and_tag
    if: ${{ inputs.next_release_branch != '' || inputs.propagate_to_develop }}
    steps:
      - name: Setup Git
        uses: JAGT1806/repo-actions/.github/actions/setup-git@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Propagate to next release (if exists)
        if: ${{ inputs.next_release_branch != '' }}
        uses: JAGT1806/repo-actions/.github/actions/propagate-release@main
        with:
          from_branch: ${{ inputs.release_branch }}
          to_branch: ${{ inputs.next_release_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Propagate to develop
        if: ${{ inputs.propagate_to_develop }}
        uses: JAGT1806/repo-actions/.github/actions/propagate-release@main
        with:
          from_branch: ${{ inputs.release_branch }}
          to_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
